#!/bin/bash

px () {
  export http_proxy="http://127.0.0.1:1088"
  export https_proxy=$http_proxy
  export ftp_proxy=$http_proxy
  export all_proxy=$http_proxy
  
  export HTTP_PROXY=$http_proxy
  export HTTPS_PROXY=$http_proxy
  export FTP_PROXY=$http_proxy
  export ALL_PROXY=$http_proxy
  
  export no_proxy="localhost,127.0.0.1,.local,.lan"
  export NO_PROXY="localhost,127.0.0.1,.local,.lan"

  echo ">>> Proxy set to $http_proxy."

}

unpx () {
  unset http_proxy
  unset https_proxy
  unset ftp_proxy
  unset all_proxy
  unset HTTP_PROXY
  unset HTTPS_PROXY
  unset FTP_PROXY
  unset ALL_PROXY

  unset no_proxy
  unset NO_PROXY

  echo ">>> Proxy off."

}
